// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 8);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1790239793);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1790239792);
user_pref("calendar.list.sortOrder", "28cda786-46f4-421e-b769-02d11879739c");
user_pref("calendar.registry.28cda786-46f4-421e-b769-02d11879739c.calendar-main-default", true);
user_pref("calendar.registry.28cda786-46f4-421e-b769-02d11879739c.calendar-main-in-composite", true);
user_pref("calendar.registry.28cda786-46f4-421e-b769-02d11879739c.disabled", true);
user_pref("calendar.registry.28cda786-46f4-421e-b769-02d11879739c.name", "Home");
user_pref("calendar.registry.28cda786-46f4-421e-b769-02d11879739c.type", "storage");
user_pref("calendar.registry.28cda786-46f4-421e-b769-02d11879739c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1790239791);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250110202218");
user_pref("extensions.lastAppVersion", "128.6.0");
user_pref("extensions.lastPlatformVersion", "128.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"4156661b-6847-49d0-b388-07be873d2539\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "794ebb21-24a2-472d-bc9f-b00b23a415a");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.6.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1790239774);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20250110202218");
